"""add smart shift scheduling

Revision ID: cf0f501f17f7
Revises: c3f0b1a2d4e6
Create Date: 2026-09-07 13:27:07.196336

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa

from app.core.timezone import UTCDateTime


# revision identifiers, used by Alembic.
revision: str = 'cf0f501f17f7'
down_revision: Union[str, Sequence[str], None] = 'c3f0b1a2d4e6'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('shifts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('start_time', sa.Time(), nullable=False),
    sa.Column('end_time', sa.Time(), nullable=False),
    sa.Column('break_start_time', sa.Time(), nullable=True),
    sa.Column('break_end_time', sa.Time(), nullable=True),
    sa.Column('late_tolerance_minutes', sa.Integer(), nullable=False),
    sa.Column('early_checkin_minutes', sa.Integer(), nullable=False),
    sa.Column('is_overnight', sa.Boolean(), nullable=False),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_shifts_code'), 'shifts', ['code'], unique=True)
    op.create_index(op.f('ix_shifts_id'), 'shifts', ['id'], unique=False)
    op.create_table('work_schedules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(length=100), nullable=False),
    sa.Column('code', sa.String(length=50), nullable=False),
    sa.Column('description', sa.Text(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.PrimaryKeyConstraint('id')
    )
    op.create_index(op.f('ix_work_schedules_code'), 'work_schedules', ['code'], unique=True)
    op.create_index(op.f('ix_work_schedules_id'), 'work_schedules', ['id'], unique=False)
    op.create_table('schedule_rules',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('shift_id', sa.Integer(), nullable=True),
    sa.Column('day_of_week', sa.Integer(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['schedule_id'], ['work_schedules.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['shift_id'], ['shifts.id'], ondelete='SET NULL'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('schedule_id', 'day_of_week', name='uq_schedule_rule_day')
    )
    op.create_index(op.f('ix_schedule_rules_schedule_id'), 'schedule_rules', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_schedule_rules_shift_id'), 'schedule_rules', ['shift_id'], unique=False)
    op.create_table('schedule_assignments',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('employee_id', sa.Integer(), nullable=False),
    sa.Column('schedule_id', sa.Integer(), nullable=False),
    sa.Column('effective_from', sa.Date(), nullable=False),
    sa.Column('effective_to', sa.Date(), nullable=True),
    sa.Column('is_active', sa.Boolean(), nullable=False),
    sa.Column('created_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.Column('updated_at', UTCDateTime(), server_default=sa.text('(CURRENT_TIMESTAMP)'), nullable=False),
    sa.ForeignKeyConstraint(['employee_id'], ['employees.id'], ondelete='CASCADE'),
    sa.ForeignKeyConstraint(['schedule_id'], ['work_schedules.id'], ondelete='CASCADE'),
    sa.PrimaryKeyConstraint('id'),
    sa.UniqueConstraint('employee_id', 'schedule_id', 'effective_from', name='uq_employee_schedule_assignment')
    )
    op.create_index(op.f('ix_schedule_assignments_employee_id'), 'schedule_assignments', ['employee_id'], unique=False)
    op.create_index(op.f('ix_schedule_assignments_schedule_id'), 'schedule_assignments', ['schedule_id'], unique=False)
    op.create_index(op.f('ix_employees_id'), 'employees', ['id'], unique=False)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_index(op.f('ix_employees_id'), table_name='employees')
    op.drop_index(op.f('ix_schedule_assignments_schedule_id'), table_name='schedule_assignments')
    op.drop_index(op.f('ix_schedule_assignments_employee_id'), table_name='schedule_assignments')
    op.drop_table('schedule_assignments')
    op.drop_index(op.f('ix_schedule_rules_shift_id'), table_name='schedule_rules')
    op.drop_index(op.f('ix_schedule_rules_schedule_id'), table_name='schedule_rules')
    op.drop_table('schedule_rules')
    op.drop_index(op.f('ix_work_schedules_id'), table_name='work_schedules')
    op.drop_index(op.f('ix_work_schedules_code'), table_name='work_schedules')
    op.drop_table('work_schedules')
    op.drop_index(op.f('ix_shifts_id'), table_name='shifts')
    op.drop_index(op.f('ix_shifts_code'), table_name='shifts')
    op.drop_table('shifts')
    # ### end Alembic commands ###
