"""make user and employee ids database generated

Revision ID: e1f2a3b4c5d6
Revises: d7a8b9c0e1f2
Create Date: 2026-09-07 00:00:00.000000

"""
from typing import Sequence, Union

from alembic import op


revision: str = "e1f2a3b4c5d6"
down_revision: Union[str, Sequence[str], None] = "d7a8b9c0e1f2"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def _ensure_generated_id(table_name: str) -> None:
    op.execute(
        f"""
        DO $$
        BEGIN
            IF NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = '{table_name}'
                  AND column_name = 'id'
                  AND is_identity = 'YES'
            ) AND NOT EXISTS (
                SELECT 1
                FROM information_schema.columns
                WHERE table_schema = 'public'
                  AND table_name = '{table_name}'
                  AND column_name = 'id'
                  AND column_default IS NOT NULL
            ) THEN
                ALTER TABLE public.{table_name}
                    ALTER COLUMN id ADD GENERATED BY DEFAULT AS IDENTITY;
            END IF;
        END $$;
        """
    )
    op.execute(
        f"""
        SELECT setval(
            pg_get_serial_sequence('public.{table_name}', 'id'),
            COALESCE((SELECT MAX(id) FROM public.{table_name}), 1),
            (SELECT MAX(id) IS NOT NULL FROM public.{table_name})
        )
        """
    )


def upgrade() -> None:
    _ensure_generated_id("users")
    _ensure_generated_id("employees")


def downgrade() -> None:
    op.execute(
        "ALTER TABLE public.users ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )
    op.execute(
        "ALTER TABLE public.employees ALTER COLUMN id DROP IDENTITY IF EXISTS"
    )